//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Recursos.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADM_Cars.
        /// </summary>
        internal static string ABM_Autos {
            get {
                return ResourceManager.GetString("ABM_Autos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AMD_Drivers.
        /// </summary>
        internal static string ABM_Choferes {
            get {
                return ResourceManager.GetString("ABM_Choferes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AMD_Clients.
        /// </summary>
        internal static string ABM_Clientes {
            get {
                return ResourceManager.GetString("ABM_Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADM_Owners.
        /// </summary>
        internal static string ABM_Dueños {
            get {
                return ResourceManager.GetString("ABM_Dueños", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADM_Orders.
        /// </summary>
        internal static string ABM_Pedido {
            get {
                return ResourceManager.GetString("ABM_Pedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADM_Users.
        /// </summary>
        internal static string ABM_Usuarios {
            get {
                return ResourceManager.GetString("ABM_Usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        internal static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update.
        /// </summary>
        internal static string Actualizar {
            get {
                return ResourceManager.GetString("Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update_User.
        /// </summary>
        internal static string Actualizar_Usuario {
            get {
                return ResourceManager.GetString("Actualizar_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM_Autos.
        /// </summary>
        internal static string ADM_Cars {
            get {
                return ResourceManager.GetString("ADM_Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM_Pedido.
        /// </summary>
        internal static string ADM_Orders {
            get {
                return ResourceManager.GetString("ADM_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM_Dueños.
        /// </summary>
        internal static string ADM_Owners {
            get {
                return ResourceManager.GetString("ADM_Owners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM_Usuarios.
        /// </summary>
        internal static string ADM_Users {
            get {
                return ResourceManager.GetString("ADM_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        internal static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas_las_Patentes.
        /// </summary>
        internal static string All_the_Patents {
            get {
                return ResourceManager.GetString("All_the_Patents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New_User.
        /// </summary>
        internal static string Alta_Usuario {
            get {
                return ResourceManager.GetString("Alta_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM_Clientes.
        /// </summary>
        internal static string AMD_Clients {
            get {
                return ResourceManager.GetString("AMD_Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABM_Choferes.
        /// </summary>
        internal static string AMD_Drivers {
            get {
                return ResourceManager.GetString("AMD_Drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad_Pasajeros.
        /// </summary>
        internal static string Amount_Passengers {
            get {
                return ResourceManager.GetString("Amount_Passengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last_Name.
        /// </summary>
        internal static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open_Spreadsheets.
        /// </summary>
        internal static string Apertura_Planilla {
            get {
                return ResourceManager.GetString("Apertura_Planilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CARS.
        /// </summary>
        internal static string AUTOS {
            get {
                return ResourceManager.GetString("AUTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BACKUP_RESTORE.
        /// </summary>
        internal static string BACKUP_RESTORE {
            get {
                return ResourceManager.GetString("BACKUP_RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DB.
        /// </summary>
        internal static string BD {
            get {
                return ResourceManager.GetString("BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BITÁCORA.
        /// </summary>
        internal static string BINNACLE {
            get {
                return ResourceManager.GetString("BINNACLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BINNACLE.
        /// </summary>
        internal static string BITÁCORA {
            get {
                return ResourceManager.GetString("BITÁCORA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search_Spreadsheets.
        /// </summary>
        internal static string Buscar_Planilla {
            get {
                return ResourceManager.GetString("Buscar_Planilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Street.
        /// </summary>
        internal static string Calle {
            get {
                return ResourceManager.GetString("Calle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount_Passengers.
        /// </summary>
        internal static string Cantidad_Pasajeros {
            get {
                return ResourceManager.GetString("Cantidad_Pasajeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AUTOS.
        /// </summary>
        internal static string CARS {
            get {
                return ResourceManager.GetString("CARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Celular.
        /// </summary>
        internal static string Cellphone {
            get {
                return ResourceManager.GetString("Cellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cellphone.
        /// </summary>
        internal static string Celular {
            get {
                return ResourceManager.GetString("Celular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SING_OFF.
        /// </summary>
        internal static string CERRAR_SESIÓN {
            get {
                return ResourceManager.GetString("CERRAR_SESIÓN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Driver.
        /// </summary>
        internal static string Chofer {
            get {
                return ResourceManager.GetString("Chofer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DRIVER.
        /// </summary>
        internal static string CHOFERES {
            get {
                return ResourceManager.GetString("CHOFERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nro_Cliente.
        /// </summary>
        internal static string Client_Number {
            get {
                return ResourceManager.GetString("Client_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CLIENTS.
        /// </summary>
        internal static string CLIENTES {
            get {
                return ResourceManager.GetString("CLIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CLIENTES.
        /// </summary>
        internal static string CLIENTS {
            get {
                return ResourceManager.GetString("CLIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection_DB.
        /// </summary>
        internal static string Conexión_BD {
            get {
                return ResourceManager.GetString("Conexión_BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SETTING.
        /// </summary>
        internal static string CONFIGURACIÓN {
            get {
                return ResourceManager.GetString("CONFIGURACIÓN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conexión_BD.
        /// </summary>
        internal static string Connection_DB {
            get {
                return ResourceManager.GetString("Connection_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta.
        /// </summary>
        internal static string Consult {
            get {
                return ResourceManager.GetString("Consult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consult.
        /// </summary>
        internal static string Consulta {
            get {
                return ResourceManager.GetString("Consulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User_Consult.
        /// </summary>
        internal static string Consulta_Usuario {
            get {
                return ResourceManager.GetString("Consulta_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultation_Users_and_Patents.
        /// </summary>
        internal static string Consulta_Usuarios_y_Patentes {
            get {
                return ResourceManager.GetString("Consulta_Usuarios_y_Patentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ConsultFamiliesandPatents.
        /// </summary>
        internal static string ConsultaFamiliasyPantentes {
            get {
                return ResourceManager.GetString("ConsultaFamiliasyPantentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consult.
        /// </summary>
        internal static string Consultar {
            get {
                return ResourceManager.GetString("Consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta_Usuarios_y_Patentes.
        /// </summary>
        internal static string Consultation_Users_and_Patents {
            get {
                return ResourceManager.GetString("Consultation_Users_and_Patents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ConsultaFamiliasyPantentes.
        /// </summary>
        internal static string ConsultFamiliesandPatents {
            get {
                return ResourceManager.GetString("ConsultFamiliesandPatents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create_Family.
        /// </summary>
        internal static string Crear_Familia {
            get {
                return ResourceManager.GetString("Crear_Familia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear_Familia.
        /// </summary>
        internal static string Create_Family {
            get {
                return ResourceManager.GetString("Create_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BD.
        /// </summary>
        internal static string DB {
            get {
                return ResourceManager.GetString("DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar_Familia.
        /// </summary>
        internal static string Delete_Family {
            get {
                return ResourceManager.GetString("Delete_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Depuration.
        /// </summary>
        internal static string Depuración {
            get {
                return ResourceManager.GetString("Depuración", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Depuración.
        /// </summary>
        internal static string Depuration {
            get {
                return ResourceManager.GetString("Depuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dest_Domicilio.
        /// </summary>
        internal static string Dest_address {
            get {
                return ResourceManager.GetString("Dest_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dest_address.
        /// </summary>
        internal static string Dest_Domicilio {
            get {
                return ResourceManager.GetString("Dest_Domicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PASSPORT.
        /// </summary>
        internal static string DNI {
            get {
                return ResourceManager.GetString("DNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chofer.
        /// </summary>
        internal static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CHOFERES.
        /// </summary>
        internal static string DRIVERS {
            get {
                return ResourceManager.GetString("DRIVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OWNERS.
        /// </summary>
        internal static string DUEÑOS {
            get {
                return ResourceManager.GetString("DUEÑOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete_Family.
        /// </summary>
        internal static string Eliminar_Familia {
            get {
                return ResourceManager.GetString("Eliminar_Familia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a STATISTICS.
        /// </summary>
        internal static string ESTADÍSTICA {
            get {
                return ResourceManager.GetString("ESTADÍSTICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas_las_Familias.
        /// </summary>
        internal static string Every_Family {
            get {
                return ResourceManager.GetString("Every_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Family_Patents.
        /// </summary>
        internal static string Familia_Patentes {
            get {
                return ResourceManager.GetString("Familia_Patentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Families.
        /// </summary>
        internal static string Familias {
            get {
                return ResourceManager.GetString("Familias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User_Families.
        /// </summary>
        internal static string Familias_del_Usuario {
            get {
                return ResourceManager.GetString("Familias_del_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familias.
        /// </summary>
        internal static string Families {
            get {
                return ResourceManager.GetString("Families", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre_Familia.
        /// </summary>
        internal static string Family_name {
            get {
                return ResourceManager.GetString("Family_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia_Patentes.
        /// </summary>
        internal static string Family_Patents {
            get {
                return ResourceManager.GetString("Family_Patents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reservation_Date.
        /// </summary>
        internal static string Fecha_Reserva {
            get {
                return ResourceManager.GetString("Fecha_Reserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piso_Dep_Puerta.
        /// </summary>
        internal static string floor_apart_door {
            get {
                return ResourceManager.GetString("floor_apart_door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Management_of_Cars.
        /// </summary>
        internal static string Gestión_de_Remises {
            get {
                return ResourceManager.GetString("Gestión_de_Remises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origen_Domicilio.
        /// </summary>
        internal static string Home_Origin {
            get {
                return ResourceManager.GetString("Home_Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id_Usuario.
        /// </summary>
        internal static string Id_User {
            get {
                return ResourceManager.GetString("Id_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id_User.
        /// </summary>
        internal static string Id_Usuario {
            get {
                return ResourceManager.GetString("Id_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Languages.
        /// </summary>
        internal static string Idiomas {
            get {
                return ResourceManager.GetString("Idiomas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter.
        /// </summary>
        internal static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idiomas.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        internal static string Last_Name {
            get {
                return ResourceManager.GetString("Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location.
        /// </summary>
        internal static string Localidad {
            get {
                return ResourceManager.GetString("Localidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Localidad.
        /// </summary>
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mail.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión_de_Remises.
        /// </summary>
        internal static string Management_of_Cars {
            get {
                return ResourceManager.GetString("Management_of_Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo_Backup.
        /// </summary>
        internal static string New_Backup {
            get {
                return ResourceManager.GetString("New_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo_Pedido.
        /// </summary>
        internal static string New_Order {
            get {
                return ResourceManager.GetString("New_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alta_Usuario.
        /// </summary>
        internal static string New_User {
            get {
                return ResourceManager.GetString("New_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Family_name.
        /// </summary>
        internal static string Nombre_Familia {
            get {
                return ResourceManager.GetString("Nombre_Familia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        internal static string Nombre_Usuario {
            get {
                return ResourceManager.GetString("Nombre_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Client_Number.
        /// </summary>
        internal static string Nro_Cliente {
            get {
                return ResourceManager.GetString("Nro_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New_Backup.
        /// </summary>
        internal static string Nuevo_Backup {
            get {
                return ResourceManager.GetString("Nuevo_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New_Order.
        /// </summary>
        internal static string Nuevo_Pedido {
            get {
                return ResourceManager.GetString("Nuevo_Pedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number.
        /// </summary>
        internal static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number.
        /// </summary>
        internal static string Número {
            get {
                return ResourceManager.GetString("Número", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apertura_Planilla.
        /// </summary>
        internal static string Open_Spreadsheets {
            get {
                return ResourceManager.GetString("Open_Spreadsheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PEDIDOS.
        /// </summary>
        internal static string ORDERS {
            get {
                return ResourceManager.GetString("ORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home_Origin.
        /// </summary>
        internal static string Origen_Domicilio {
            get {
                return ResourceManager.GetString("Origen_Domicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DUEÑOS.
        /// </summary>
        internal static string OWNERS {
            get {
                return ResourceManager.GetString("OWNERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI.
        /// </summary>
        internal static string PASSPORT {
            get {
                return ResourceManager.GetString("PASSPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Family_Patents.
        /// </summary>
        internal static string Patentes_de_Famlia {
            get {
                return ResourceManager.GetString("Patentes_de_Famlia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User_Patents.
        /// </summary>
        internal static string Patentes_del_Usuario {
            get {
                return ResourceManager.GetString("Patentes_del_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ORDERS.
        /// </summary>
        internal static string PEDIDOS {
            get {
                return ResourceManager.GetString("PEDIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a floor_apart_door.
        /// </summary>
        internal static string Piso_Dep_Puerta {
            get {
                return ResourceManager.GetString("Piso_Dep_Puerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia.
        /// </summary>
        internal static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Province.
        /// </summary>
        internal static string Provincia {
            get {
                return ResourceManager.GetString("Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        internal static string Registrar {
            get {
                return ResourceManager.GetString("Registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha_Reserva.
        /// </summary>
        internal static string Reservation_Date {
            get {
                return ResourceManager.GetString("Reservation_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restore_Backup.
        /// </summary>
        internal static string Restaurar_Backup {
            get {
                return ResourceManager.GetString("Restaurar_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restaurar_Backup.
        /// </summary>
        internal static string Restore_Backup {
            get {
                return ResourceManager.GetString("Restore_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar_Planilla.
        /// </summary>
        internal static string Search_Spreadsheets {
            get {
                return ResourceManager.GetString("Search_Spreadsheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servidor.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server.
        /// </summary>
        internal static string Servidor {
            get {
                return ResourceManager.GetString("Servidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONFIGURACIÓN.
        /// </summary>
        internal static string SETTING {
            get {
                return ResourceManager.GetString("SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CERRAR_SESIÓN.
        /// </summary>
        internal static string SING_OFF {
            get {
                return ResourceManager.GetString("SING_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESTADÍSTICA.
        /// </summary>
        internal static string STATISTICS {
            get {
                return ResourceManager.GetString("STATISTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calle.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a StringConnection.
        /// </summary>
        internal static string StringConexion {
            get {
                return ResourceManager.GetString("StringConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a StringConexion.
        /// </summary>
        internal static string StringConnection {
            get {
                return ResourceManager.GetString("StringConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        internal static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Every_Family.
        /// </summary>
        internal static string Todas_las_Familias {
            get {
                return ResourceManager.GetString("Todas_las_Familias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All_the_Patents.
        /// </summary>
        internal static string Todas_las_Patentes {
            get {
                return ResourceManager.GetString("Todas_las_Patentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location.
        /// </summary>
        internal static string Ubicación {
            get {
                return ResourceManager.GetString("Ubicación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar_Usuario.
        /// </summary>
        internal static string Update_User {
            get {
                return ResourceManager.GetString("Update_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta_Usuario.
        /// </summary>
        internal static string User_Consult {
            get {
                return ResourceManager.GetString("User_Consult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familias_del_Usuario.
        /// </summary>
        internal static string User_Families {
            get {
                return ResourceManager.GetString("User_Families", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patentes_del_Usuario.
        /// </summary>
        internal static string User_Patents {
            get {
                return ResourceManager.GetString("User_Patents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre_Usuario.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios_Patentes.
        /// </summary>
        internal static string Users_Patents {
            get {
                return ResourceManager.GetString("Users_Patents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users_Patents.
        /// </summary>
        internal static string Usuarios_Patentes {
            get {
                return ResourceManager.GetString("Usuarios_Patentes", resourceCulture);
            }
        }
    }
}
